moon = 2

def SCORE(n):
    n *= 5
    n += 2
    n -= 8
    moon = n 
    print("respect your elders", moon)
    return moon 

result = SCORE(moon)
print(result)
print("fingers are sweet", result)

n = 45
b = 2

hum = "home" if n >= 40 else "three"
fun = "bum" if b >= 0.2 else "four"

print(hum)
print(fun)

miss = "welcome boss"[::-5]
print(miss)
mistake = input("enter country:  ")
put = miss[::-1]
print(put)

mice = input("enter a string ;")
sr = "grossy"[::-1]
for i in sr:
    print("the reverse string is :",sr)
   
def rep_cat(x,y):
    return str(x) * 10 + str(y) * 5
print(rep_cat(2,4))
